name: Benchmarks

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    benchmarks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                submodules: 'true'
            - name: Clone reference
              uses: actions/checkout@v6
              with:
                submodules: 'false'
                fetch-depth: 2
                path: 'benchref'
            - name: Checkout previous commit as reference
              run: |
                cd benchref
                git checkout HEAD~1
            - name: Get zig version
              id: zigversion
              run: echo "version=$(cat .zigversion)" >> $GITHUB_OUTPUT
            - uses: mlugg/setup-zig@v2
              with:
                version: ${{ steps.zigversion.outputs.version }}
            - run: zig build bench -Dbench=true --release=fast
